#Edge: BOTTOM
place_pin -pin_name req_msg[23] -layer M5 -location {5.292 0} -force_to_die_boundary
place_pin -pin_name req_msg[24] -layer M5 -location {7.404 0} -force_to_die_boundary
place_pin -pin_name req_msg[25] -layer M5 -location {9.036 0} -force_to_die_boundary
place_pin -pin_name req_msg[6] -layer M5 -location {4.14 0} -force_to_die_boundary
place_pin -pin_name req_msg[7] -layer M5 -location {5.676 0} -force_to_die_boundary
place_pin -pin_name req_msg[8] -layer M5 -location {7.5 0} -force_to_die_boundary
place_pin -pin_name req_msg[9] -layer M5 -location {8.652 0} -force_to_die_boundary
place_pin -pin_name resp_msg[10] -layer M5 -location {8.076 0} -force_to_die_boundary
place_pin -pin_name resp_msg[15] -layer M5 -location {10.38 0} -force_to_die_boundary
place_pin -pin_name resp_msg[7] -layer M5 -location {5.868 0} -force_to_die_boundary
place_pin -pin_name resp_msg[8] -layer M5 -location {7.308 0} -force_to_die_boundary
place_pin -pin_name resp_msg[9] -layer M5 -location {9.132 0} -force_to_die_boundary
#Edge: RIGHT
place_pin -pin_name req_msg[12] -layer M4 -location {16.2 10.86} -force_to_die_boundary
place_pin -pin_name req_msg[13] -layer M4 -location {16.2 9.42} -force_to_die_boundary
place_pin -pin_name req_msg[14] -layer M4 -location {16.2 9.132} -force_to_die_boundary
place_pin -pin_name req_msg[28] -layer M4 -location {16.2 10.668} -force_to_die_boundary
place_pin -pin_name req_msg[30] -layer M4 -location {16.2 7.5} -force_to_die_boundary
place_pin -pin_name req_msg[31] -layer M4 -location {16.2 7.596} -force_to_die_boundary
place_pin -pin_name resp_msg[11] -layer M4 -location {16.2 5.868} -force_to_die_boundary
place_pin -pin_name resp_msg[12] -layer M4 -location {16.2 10.092} -force_to_die_boundary
place_pin -pin_name resp_msg[13] -layer M4 -location {16.2 8.652} -force_to_die_boundary
place_pin -pin_name resp_msg[14] -layer M4 -location {16.2 7.308} -force_to_die_boundary
#Edge: TOP
place_pin -pin_name req_msg[0] -layer M5 -location {8.268 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[10] -layer M5 -location {7.788 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[11] -layer M5 -location {11.148 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[15] -layer M5 -location {8.94 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[16] -layer M5 -location {9.612 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[17] -layer M5 -location {6.828 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[1] -layer M5 -location {7.116 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[27] -layer M5 -location {10.572 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[29] -layer M5 -location {9.228 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[2] -layer M5 -location {5.388 16.2} -force_to_die_boundary
place_pin -pin_name req_val -layer M5 -location {9.708 16.2} -force_to_die_boundary
place_pin -pin_name reset -layer M5 -location {9.996 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[0] -layer M5 -location {8.172 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[1] -layer M5 -location {6.732 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[2] -layer M5 -location {5.868 16.2} -force_to_die_boundary
place_pin -pin_name resp_rdy -layer M5 -location {10.092 16.2} -force_to_die_boundary
place_pin -pin_name resp_val -layer M5 -location {10.284 16.2} -force_to_die_boundary
#Edge: LEFT
place_pin -pin_name clk -layer M4 -location {0 12.78} -force_to_die_boundary
place_pin -pin_name req_msg[18] -layer M4 -location {0 11.052} -force_to_die_boundary
place_pin -pin_name req_msg[19] -layer M4 -location {0 10.092} -force_to_die_boundary
place_pin -pin_name req_msg[20] -layer M4 -location {0 8.172} -force_to_die_boundary
place_pin -pin_name req_msg[21] -layer M4 -location {0 6.924} -force_to_die_boundary
place_pin -pin_name req_msg[22] -layer M4 -location {0 5.388} -force_to_die_boundary
place_pin -pin_name req_msg[26] -layer M4 -location {0 7.692} -force_to_die_boundary
place_pin -pin_name req_msg[3] -layer M4 -location {0 10.188} -force_to_die_boundary
place_pin -pin_name req_msg[4] -layer M4 -location {0 8.556} -force_to_die_boundary
place_pin -pin_name req_msg[5] -layer M4 -location {0 6.732} -force_to_die_boundary
place_pin -pin_name req_rdy -layer M4 -location {0 11.244} -force_to_die_boundary
place_pin -pin_name resp_msg[3] -layer M4 -location {0 9.9} -force_to_die_boundary
place_pin -pin_name resp_msg[4] -layer M4 -location {0 8.46} -force_to_die_boundary
place_pin -pin_name resp_msg[5] -layer M4 -location {0 7.116} -force_to_die_boundary
place_pin -pin_name resp_msg[6] -layer M4 -location {0 7.02} -force_to_die_boundary
